Models/ErrorViewModel.cs
namespace KitchenForKiddosMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Meals/MealsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;

namespace KitchenForKiddosMVC.Models.Meals
{
    public class MealsViewModel
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }
    }
}

Models/WeekDefinition/WeekListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace KitchenForKiddosMVC.Models.WeekDefinition
{
    public class WeekListItem
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("startdate")]
        public DateTime StartDate { get; set; }

        [JsonPropertyName("enddate")]
        public DateTime EndDate { get; set; }

        [JsonPropertyName("notes")]
        [Display(Name = "Notes For The Week")]
        public string Notes { get; set; }
    }
}

Models/WeeklyCalendar/WeeklyCreate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace KitchenForKiddosMVC.Models.WeeklyCalendar
{
    public class WeeklyCreate
    {
        [JsonPropertyName("id")]
        public int DefinitionId { get; set; }

        [JsonPropertyName("dayofweek")]
        public Day_Of_Week Day_Of_Week { get; set; }

        [JsonPropertyName("breakfast")]
        public int BreakfastId { get; set; }

        [JsonPropertyName("lunch")]
        public int LunchId { get; set; }

        [JsonPropertyName("snack")]
        public int SnackId { get; set; }

        [JsonPropertyName("dinner")]
        public int DinnerId { get; set; }

    }

    public enum Day_Of_Week {Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using KitchenForKiddosMVC.Models;

namespace KitchenForKiddosMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KitchenForKiddosMVC.Services.Meals;
using Microsoft.AspNetCore.Mvc;

namespace KitchenForKiddosMVC.Controllers
{
    public class MealsController :Controller
    {
        private readonly ILogger<MealsController> _logger;
        private IMealsService _service;

        public MealsController(ILogger<MealsController> logger, IMealsService service)
        {
            _logger = logger;
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var mealLists = await _service.SeeAllMealsAsync();
            return View(mealLists);
        }
    }
}

Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace KitchenForKiddosMVC.Controllers
{
    public class RecipeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ShoppingListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace KitchenForKiddosMVC.Controllers
{
    public class ShoppingListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/WeekDefinitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc;
using KitchenForKiddosMVC.Services.WeekDefinition;

namespace KitchenForKiddosMVC.Controllers
{
    public class WeekDefinitionController : Controller
    {
        private readonly ILogger<WeekDefinitionController> _logger;
        private IWeekDefinitionService _service;

        public WeekDefinitionController(ILogger<WeekDefinitionController> logger, IWeekDefinitionService service)
        {
            _logger = logger;
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var weekLists = await _service.GetAllWeeksAsync();
            return View(weekLists); 
        }
    }
}

Controllers/WeeklyCalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace KitchenForKiddosMVC.Controllers
{
    public class WeeklyCalendarController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@model string
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Kitchen For Kiddos @Model</h1>
    <p>Pick, Schedule and Shop for easy to make meals that are loved by kids</p>
</div>

Views/Meals/Index.cshtml
@{
    ViewData["Title"] = "Meals";
}

<h1>Meals Index</h1>

Views/Recipe/Index.cshtml
@{
    ViewData["Title"] = "Recipe";
}

<h1>Recipe Index</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KitchenForKiddosMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KitchenForKiddosMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KitchenForKiddosMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeekDefinition" asp-action="Index">Week Definition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meals" asp-action="Index">Meals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeeklyCalendar" asp-action="Index">Weekly Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingList" asp-action="Index">Shopping List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KitchenForKiddosMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/ShoppingList/Index.cshtml
@{
    ViewData["Title"] = "Shopping List";
}

<h1>Shopping List Index</h1>

Views/WeekDefinition/Index.cshtml
@model IEnumerable<KitchenForKiddosMVC.Models.WeekDefinition.WeekListItem>

@{
    ViewData["Title"] = "Meal Weeks Overview";
}

<h1>Week Definition Index</h1>
<p>
    @* @Html.ActionLink("Create")*@
    <a asp-action="Create">Create</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
            </tr>
        }
    </tbody>
</table>

Views/WeeklyCalendar/Index.cshtml
@{
    ViewData["Title"] = "Weekly Calendar";
}

<h1>Weekly Calendar Index</h1>